[workspace]
resolver = "2"
members = [
	"sdk",
	"examples",
]
exclude = ["examples"]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/0xC0DE666/xai-sdk"
rust-version = "1.88"
