[package]
name = "xai-sdk"
version = "0.5.0"
edition.workspace = true
description = "xAI SDK"
documentation = "https://docs.rs/xai-sdk"
categories = ["web-programming", "asynchronous"]
keywords = ["grpc", "async", "grok"]

[lib]
name = "xai_sdk"
path = "src/lib.rs"

[dependencies]
prost = "0.14"
prost-wkt-types = "0.7"
tonic = { version = "0.14", features = ["channel", "tls-ring", "tls-native-roots"] }
tonic-prost = { version = "0.14" }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-prost-build = { version = "0.14" }
